### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [snurby7/project4#1]
It looks like your page is [throwing some HTML errors](http://validator.w3.org/check?uri=https%3A%2F%2Fglacial-cove-6887.herokuapp.com%2F&charset=%28detect+automatically%29&doctype=Inline&group=0). Can you fix these and repush to Heroku and GitHub?

**Comment by snurby7** [comment]
Fixed in latest commit 74b15e1

**Comment by chrisvfritz** [comment]
:+1: Much better!
